---
#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2024-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#
# License categorization used by the evaluator
categories:
- name: "allow"
  description: "Licenses that are allowed without review"
- name: "review"
  description: "Licenses that need to be reviewed and added to the evaluator rules"
- name: "disallow"
  description: "Licenses that are disallowed alone, but allowed in an OR rule"

categorizations:
- id: NOASSERTION
  categories:
  - "allow"
- id: NONE
  categories:
  - "allow"
- id: "Apache-2.0"
  categories:
  - "allow"
- id: "Zlib"
  categories:
  - "review"
- id: "Apache-2.0 WITH LLVM-exception"
  categories:
  - "review"
- id: "BSD-2-Clause"
  categories: 
  - "review"
- id: "BSD-3-Clause"
  categories: 
  - "review"
- id: "GPL-2.0-only"
  categories: 
  - "review"
  - "disallow"
- id: "BSL-1.0"
  categories: 
  - "review"
- id: "CC0-1.0"
  categories: 
  - "review"
- id: "FSFUL"
  categories: 
  - "review"
- id: "GPL-3.0-or-later WITH Autoconf-exception-generic-3.0"
  categories: 
  - "review"
- id: "LGPL-2.0-or-later"
  categories: 
  - "review"
  - "disallow"
- id: "LGPL-2.1-or-later"
  categories: 
  - "review"
  - "disallow"
- id: "MIT"
  categories: 
  - "review"
- id: "MPL-1.1"
  categories: 
  - "review"
- id: "TCL"
  categories: 
  - "review"
- id: "Unicode-3.0"
  categories: 
  - "review"
- id: "Unlicense"
  categories: 
  - "review"